@echo off
@echo 🚀 Iniciando servidor em background...
@echo O servidor será executado em 3 segundos...
timeout 3
REM Usar PowerShell para executar o servidor em background e manter o processo independente
powershell -Command "Start-Process python -ArgumentList 'server.py --silent' -WindowStyle Hidden"

@echo 🌐 Aguardando servidor inicializar...
timeout 5

@echo 🔗 Iniciando ngrok para expor o servidor...
ngrok http 127.0.0.1:5000